### ISSUE TITLE
Can not compile hsdev-0.3.0.1 with stack

### ISSUE THREAD

**Issue by ShrykeWindgrace** [mvoidex/hsdev#71]
When I run `stack unpack hsdev && cd hsdev-0.3.0.1 && stack init --solver && stack build`,
I get 
```
src\HsDev\Tools\HDocs.hs:62:37: error:
        * No instance for (Monoid (GhcM [Map String String]))
            arising from a use of `mempty'
        * In the first argument of `return', namely `mempty'
          In the second argument of `(>>)', namely `return mempty'
          In the expression: notSupported >> return mempty
       |
    62 | hdocsy _ _ = notSupported >> return mempty
       |                                     ^^^^^^

    src\HsDev\Tools\HDocs.hs:79:13: error:
        * No instance for (Log.MonadLog ((->) [String]))
            arising from a use of `notSupported'
        * In the first argument of `(>>)', namely `notSupported'
          In the expression: notSupported >> return mempty
          In an equation for `hdocs':
              hdocs _ _ = notSupported >> return mempty
       |
    79 | hdocs _ _ = notSupported >> return mempty
       |             ^^^^^^^^^^^^

    src\HsDev\Tools\HDocs.hs:79:36: error:
        * No instance for (Monoid (GhcM (Map String String)))
            arising from a use of `mempty'
        * In the first argument of `return', namely `mempty'
          In the second argument of `(>>)', namely `return mempty'
          In the expression: notSupported >> return mempty
       |
    79 | hdocs _ _ = notSupported >> return mempty
       |                                    ^^^^^^
```
(the `^^^^^` are under `mempty` and `notSupported ` ). I see this problem both on win10 and ubuntu16.04, both machines run with `stack-1.6.3` .

What is the correct approach to solve it? Is there a way for a stack build to ignore the docs?

**Comment by mvoidex** [comment]
Building without docs broken, fixing in new version.
You can clone repo at tag '0.3.0.2' and there's `stack.yaml` for `lst-10.3`

**Comment by mvoidex** [comment]
Uploaded [hsdev-0.3.0.3](http://hackage.haskell.org/package/hsdev-0.3.0.3) with fix

**Comment by ShrykeWindgrace** [comment]
The version 0.3.0.3 builds well on both win10 and ubuntu16.04. Thank you very much!
